backend/controllers/CalculatorController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use backend\components\Calculator;

/**
 * Site controller
 */
class CalculatorController extends Controller
{
    public function actionIndex()
    {   $model = \Yii::createObject(['class' => Calculator::className()]);

        if($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $result = $model->calculate();

            return $this->render('index', ['model' => $model, 'result' => $result]);
        }
        return $this->render('index', ['model' => $model]);
    }
}

backend/controllers/CartController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\Product;
use backend\models\Cart;
use backend\models\Order;
/**
 * Site controller
 */
class CartController extends Controller
{
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['add-item', 'cart', 'update','insert-order'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],

        ];
    }

    public function actionAddItem($id)
    {        
        if(Cart::add_to_cart($id))
        {
            Yii::$app->session->setFlash('success', "Product successfuly added to cart!");
        } else {
            Yii::$app->session->setFlash('fail', "Product not successfuly added to cart!");
        }
        return $this->redirect(['/product/all-product/']);
    }

    public function actionCart()
    {
        return $this->render('cart');               
        
    }
    public function actionUpdate($product_name)
    {
        if(Cart::update_cart($product_name))
        {
            Yii::$app->session->setFlash('success', "Product successfuly delete!");
        } else {
            Yii::$app->session->setFlash('fail', "Product not successfuly delete!");
        }
        $this->redirect(['cart']);
    }

    public function actionInsertOrder()
    {

        $model = \Yii::createObject(['class' => Order::className()]);

        $user = \Yii::$app->user->identity;

        if(!empty($user))
        {
            $user->link('orders',$model);
            Yii::$app->session->setFlash('success', "Order successfuly insert!");
        } else {
            Yii::$app->session->setFlash('fail', "Order not successfuly insert!");
        }

        $this->redirect(['/product/checkout/']);
        
    }
}

backend/controllers/ProductController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\Product;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use backend\models\OrderSearch;
use backend\models\Cart;
use backend\models\Order;
/**
 * Site controller
 */
class ProductController extends Controller
{
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['add-product','all-product', 'edit-product','cart', 'checkout','orders'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],

        ];
    }

    public function actionAddProduct()
    {
    	$model = \Yii::createObject(['class' => Product::className()]);

        $model->load(Yii::$app->request->post());

    	if($model->load(Yii::$app->request->post()))
    	{
            $model->image = UploadedFile::getInstance($model, 'image');
            if ($model->save()) {
                if($model->upload())
                {
                    Yii::$app->session->setFlash('success', "Product successfuly added!");
                } else {
                    Yii::$app->session->setFlash('fail', "Product not added!");
                }
            }
    		
    	} 

    	return $this->render('addproduct',['title' => 'Add product', 'but_name' => 'Add']);
    	
    	
    }

    public function actionAllProduct()
    {
        return $this->render('allproduct');    	
    }

    public function actionEditProduct($id)
    {	
    	$model = Product::findOne($id);
        if (!$model) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    	if($model->load(Yii::$app->request->post()) && $model->validate())
    	{
    		if($model->save())
    		{
    			Yii::$app->session->setFlash('success', "Product successfuly update!");
    		} else {
    			Yii::$app->session->setFlash('fail', "Product not update!");
    		}
    	} 
    	
        return $this->render('editproduct', ['title' => 'Edit product', 'but_name' => 'Update', 'id' => $id]);
    	
    	
    }


    public function actionCheckout()
    {
        return $this->render('checkout');    	
    }

    public function actionOrders()
    {
        $model = \Yii::createObject(['class' => OrderSearch::className()]);

    	return $this->render('orders', ['model' => $model]);
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\NewUser;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'register'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionRegister()
    {
        $model = new NewUser();
        if($model->load(Yii::$app->request->post()) && $model->validate()) {
           if( $model->insert_new_user(Yii::$app->request->post())) {

                return $this->render('register', [
                    'model' => $model,
                'success' => true,
            ]);
           }
        } else {
            return $this->render('register', [
                'model' => $model,
            ]);
        }
    }
}

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
        $menuItems[] = ['label' => 'Register', 'url' => ['/site/register']];
    } else {
        $menuItems[] = ['label' => 'Calculator', 'url' => ['/calculator/index']];
        $menuItems[] = ['label' => 'Cart', 'url' => ['/cart/cart']];
        $menuItems[] = ['label' => 'All orders', 'url' => ['/product/orders']];
        $menuItems[] = ['label' => 'All product', 'url' => ['/product/all-product']];
        $menuItems[] = ['label' => 'Add product', 'url' => ['/product/add-product']];
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>