backend/models/Product.php
<?php
namespace backend\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;
use backend\models\Order;
/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class Product extends ActiveRecord
{
    const SCENARIO_ADD = 'add';
    const SCENARIO_EDIT = 'edit';

	public function rules()
    {
        return [
            [['product_name','price','quantity'], 'required'],
            [['created_at','updated_at'],'trim'],
            [['quantity', 'price'], 'integer'],
            [['image'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg', 'on' => self::SCENARIO_ADD],
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    public function check_product($id)
    {
    	$product = $this->findOne($id);
    	if($product->quantity != 0)
    	{
    		return $product; 
    	} else {
    		return false;
    	}
    }

    public function upload()
    {
        if ($this->validate()) {
             $this->image->saveAs(__DIR__.'/../../uploads/' . $this->image->baseName . '.' . $this->image->extension);
            return true;
        } else {
            return false;
        }
    }

}

backend/controllers/CartController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\Product;
use backend\models\Cart;
use backend\models\Order;
/**
 * Site controller
 */
class CartController extends Controller
{
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['add-item', 'cart', 'update','insert-order'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],

        ];
    }

    public function actionAddItem($id)
    {        
        if(Cart::add_to_cart($id))
        {
            Yii::$app->session->setFlash('success', "Product successfuly added to cart!");
        } else {
            Yii::$app->session->setFlash('fail', "Product not successfuly added to cart!");
        }
        return $this->redirect(['/product/all-product/']);
    }

    public function actionCart()
    {
        return $this->render('cart');               
        
    }
    public function actionUpdate($product_name)
    {
        if(Cart::update_cart($product_name))
        {
            Yii::$app->session->setFlash('success', "Product successfuly delete!");
        } else {
            Yii::$app->session->setFlash('fail', "Product not successfuly delete!");
        }
        $this->redirect(['cart']);
    }

    public function actionInsertOrder()
    {

        $model = \Yii::createObject(['class' => Order::className()]);

        $user = \Yii::$app->user->identity;

        if(!empty($user))
        {
            $user->link('orders',$model);
            Yii::$app->session->setFlash('success', "Order successfuly insert!");
        } else {
            Yii::$app->session->setFlash('fail', "Order not successfuly insert!");
        }

        $this->redirect(['/product/checkout/']);
        
    }
}

backend/controllers/ProductController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\Product;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use backend\models\OrderSearch;
use backend\models\Cart;
use backend\models\Order;
/**
 * Site controller
 */
class ProductController extends Controller
{
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['add-product','all-product', 'edit-product','cart', 'checkout','orders'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],

        ];
    }

    public function actionAddProduct()
    {
    	$model = \Yii::createObject(['class' => Product::className()]);

        $model->load(Yii::$app->request->post());

    	if($model->load(Yii::$app->request->post()))
    	{
            $model->image = UploadedFile::getInstance($model, 'image');
            if ($model->save()) {
                if($model->upload())
                {
                    Yii::$app->session->setFlash('success', "Product successfuly added!");
                } else {
                    Yii::$app->session->setFlash('fail', "Product not added!");
                }
            }
    		
    	} 

    	return $this->render('addproduct',['title' => 'Add product', 'but_name' => 'Add']);
    	
    	
    }

    public function actionAllProduct()
    {
        return $this->render('allproduct');    	
    }

    public function actionEditProduct($id)
    {	
    	$model = Product::findOne($id);
        if (!$model) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    	if($model->load(Yii::$app->request->post()) && $model->validate())
    	{
    		if($model->save())
    		{
    			Yii::$app->session->setFlash('success', "Product successfuly update!");
    		} else {
    			Yii::$app->session->setFlash('fail', "Product not update!");
    		}
    	} 
    	
        return $this->render('editproduct', ['title' => 'Edit product', 'but_name' => 'Update', 'id' => $id]);
    	
    	
    }


    public function actionCheckout()
    {
        return $this->render('checkout');    	
    }

    public function actionOrders()
    {
        $model = \Yii::createObject(['class' => OrderSearch::className()]);

    	return $this->render('orders', ['model' => $model]);
    }
}

backend/views/product/addproduct.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use backend\models\Product;

$this->title = $title;
$model = \Yii::createObject(['class' => Product::className()]);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill new product:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form', 'options' => ['enctype' => 'multipart/form-data']]); ?>

                <?= $form->field($model, 'product_name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'price') ?>

                <?= $form->field($model, 'quantity') ?>

                <?= $form->field($model, 'image')->fileInput() ?>

                <div class="form-group">
                    <?= Html::submitButton($but_name, ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/product/allproduct.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use backend\models\Product;
use yii\data\ActiveDataProvider;

$query = Product::find();

$provider = new ActiveDataProvider([
    'query' => $query,
    'pagination' => [
        'pageSize' => 3,
    ],
]);

$this->title = 'All products';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-lg-5">


         <?= yii\grid\GridView::widget([
        'dataProvider' => $provider,
        'columns' => [
            [
                'label' => 'id', 
                'attribute' => 'id'
            ],
            [
                'label'     => 'Product name', 
                'format'    => 'raw',
                'value'     => function($product){
                    return $product->product_name;                     
                }
            ],
            [
                'label'     => 'Price', 
                'format'    => 'raw',
                'value'     => function($product){                    
                    
                    return $product->price;                     
                }
            ],
            [
                'label'     => 'Quantity', 
                'format'    => 'raw',
                'value'     => function($product){                    
                    
                    return $product->quantity;                     
                }
            ],
            [
                'label'     => 'Product image',
                'format'    => 'raw',
                'value'     => function($product){
                    return Html::img('@upload/'.$product->image, ['style' => ['width' => '100px', 'height' => '100px']]);
                }
            ],
            [
                'label'     => '', 
                'format'    => 'raw',
                'value'     => function($product){                  
                    
                    return Html::a('Add to cart', ['/cart/add-item', 'id' => $product->id], ['class' => 'profile-link']);
                }
            ],
            [
                'label'     => '', 
                'format'    => 'raw',
                'value'     => function($product){                  
                    
                    return Html::a('Edit', ['product/edit-product', 'id' => $product->id], ['class' => 'profile-link']);
                }
            ],
        ]
    ]);

    ?>
        </div>
    </div>
</div>




                

            

backend/views/product/checkout.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use backend\models\Cart;

$cart = Cart::get_cart();
$this->title = 'Checkout';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>


    <div class="row">
        <div class="col-lg-5">
        <?php if(isset($mess)): ?>
            <p><?=$mess?></p>
        <?php endif;?>
        <?php if(!empty($cart)): ?>
            <?php $form = ActiveForm::begin(['id' => 'all_product']); ?>
            <?php foreach ($cart as $key => $item):?>
                <div style="border: 2px solid black;">
                <p>Product name: <?=$item['product_name']?></p>
                <p>Product price: <?=$item['price']?></p>
                <p>Quantity: <?=$item['quantity']?></p>               
                </div>
            <?php endforeach; ?>
            <?= Html::a('Order', ['/cart/insert-order'], ['class' => 'profile-link']) ?><br>
            <?php ActiveForm::end(); ?>
        <?php endif; ?>
        </div>
    </div>
</div>

backend/views/product/editproduct.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use backend\models\Product;

$this->title = $title;
$model = \Yii::createObject(['class' => Product::className()])->findOne($id);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill new product:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'product_name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'price') ?>

                <?= $form->field($model, 'quantity') ?>

                <div class="form-group">
                    <?= Html::submitButton($but_name, ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/product/orders.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use backend\components\Calculator;


$this->title = 'Orders';
$this->params['breadcrumbs'][] = $this->title;

$provider = $model->search();
?>

<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= yii\grid\GridView::widget([
        'dataProvider' => $provider,
        'columns' => [
            [
                'label' => 'id', 
                'attribute' => 'id'
            ],
            [
                'label'     => 'user', 
                'format'    => 'raw',
                'value'     => function($order){
                    return $order['user']->username;                     
                }
            ],
            [
                'label'     => 'Order detail', 
                'format'    => 'raw',
                'value'     => function($order){
                    
                    $mess = '';
                    foreach ($order['items'] as $key => $item) {
                        $mess .= 'Product : '.$item->product_name.' '.Html::img('@upload/'.$item->image, ['style' => ['width' => '100px', 'height' => '100px']]) .' count : '. $order['orderDetails'][$key]['count'].' price '.$item->price.'<br>';
                    }
                    return $mess;                     
                }
            ],
            [
                'label'     => 'total', 
                'format'    => 'raw',
                'value'     => function($order){                  
                    
                    return $order->totalPrice;                     
                }
            ],
            [
                'label'     => 'status', 
                'format'    => 'raw',
                'value'     => function($order){                  
                    
                    return $order->status;                     
                }
            ],

        ]
    ]);

    ?>
    <div class="row">
        <div class="col-lg-5">

        </div>
    </div>
</div>